# Generated by Django 3.0.5 on 2020-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_sentemail_address_forwarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='unsub_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='verif_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
