# Generated by Django 3.0.5 on 2020-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='api_name',
            field=models.CharField(choices=[], db_index=True, max_length=3),
        ),
    ]
